[workspace]
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge", "nodefaults"]
name = "geojupyter-pixi-docker-image"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12"
jupyterhub-singleuser = "*"
jupyterlab = ">=4.4.2"
jupyterlab-favorites = "*"
jupyter-collaboration = "*"
jupyter-server-proxy = "*"
jupyterlab-myst = "*"
jupyterlab-geojson = "*"
nbdime = "*"
dask = "*"
boto3 = "*"
s3fs = "*"
urllib3 = "~=1.26.19"
numpy = "*"
matplotlib = "*"
ipympl = "*"
hvplot = "*"
pandas = "*"
scipy = "*"
xarray = "*"
jupytergis = ">=0.5.0"
leafmap = "*"
folium = "*"
geopandas = "*"
gdal = "*"
geos = "*"
geotiff = "*"
h5netcdf = "*"
h5py = "*"
rasterio = "*"
rioxarray = "*"
cartopy = "*"
shapely = "*"
geoviews = "*"
pystac-client = "*"
intake-stac = "*"
intake-xarray = "<2"
icepyx = ">=1.3.0,<2"
mystmd = "*"
typst = "*"
ruff = "*"
pre-commit = "*"
gh = "*"
gh-scoped-creds = "*"
